[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
splyce-lending-admin = "Aw7yu86xFtMZmcq1ujU5KA8gwjJ3CbbfFES34eGJowDy"
splyce-lending-fee = "3v2AAnwazqYadWGLxg6sv7KATwed8GpAHYg1uP2PaQfv"
splyce_lending = "6LQmSxSmq8mTSBqTcufK9eJXqTyrcQx8BYy2qM8CMFpr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
